import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react'

import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import  Input  from '@mui/material'
import Grid from '@mui/material/Grid'
import TextField from '@mui/material/TextField';

export default function Home() {

  useEffect(() => {
    console.log("test");
  }, []);

  /*
    Name: ${name}
    Size: ${size}
    Inhabitants: ${inhabitants}
    Focal Points: ${focalPoints}
    Issues: ${issues}
    Trade: ${trade}
    Description:
  */

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="lg">
        <div className={styles.main}>
          <Grid container spacing={2}>
            <Grid item xs={8}>
              <Typography variant="h4" component="h1" gutterBottom>
                Prompt
              </Typography>
            </Grid>
            <Grid item xs={4}>
              <TextField
                sx={{ mb: 2, width: 1}}
                id="filled-multiline-static"
                label="Input 1"
                defaultValue="Default Value"
                variant="filled"
            />
              <TextField
                sx={{ mb: 2, width: 1}}
                id="filled-multiline-static"
                label="Multi-line"
                multiline
                rows={4}
                defaultValue="Default Value"
                variant="filled"
            />
            </Grid>
          </Grid>
        </div>
      </Container>
    </>
  )
}
